AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets for wordpress docker POC

Parameters:
  WPDBNameStage:
    Type: String
    Description: Database name
  WPDBUserStage:
    Type: String
    Description: Database user
  WPDBPasswordStage:
    Type: String
    Description: Database password
  WPAuthKeyStage:
    Type: String
    Description: Auth key
  WPSecureAuthKeyStage:
    Type: String
    Description: Secure auth Key
  WPLoggedInKeyStage:
    Type: String
    Description: Logged in key
  WPNonceKeyStage:
    Type: String
    Description: Nonce key
  WPAuthSaltStage:
    Type: String
    Description: Auth salt
  WPSecureAuthSaltStage:
    Type: String
    Description: Secure auth salt
  WPLoggedInSaltStage:
    Type: String
    Description: Logged in salt
  WPNonceSaltStage:
    Type: String
    Description: Nonce salt
  WPDBNameProd:
    Type: String
    Description: Database name
  WPDBUserProd:
    Type: String
    Description: Database user
  WPDBPasswordProd:
    Type: String
    Description: Database password
  WPAuthKeyProd:
    Type: String
    Description: Auth key
  WPSecureAuthKeyProd:
    Type: String
    Description: Secure auth Key
  WPLoggedInKeyProd:
    Type: String
    Description: Logged in key
  WPNonceKeyProd:
    Type: String
    Description: Nonce key
  WPAuthSaltProd:
    Type: String
    Description: Auth salt
  WPSecureAuthSaltProd:
    Type: String
    Description: Secure auth salt
  WPLoggedInSaltProd:
    Type: String
    Description: Logged in salt
  WPNonceSaltProd:
    Type: String
    Description: Nonce salt


Resources:
  SecretsManagerSecretProd:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: wordpress/secrets/prod
      Description: Database credentials and salts for wordpress.
      SecretString: !Sub |
        {
          "WP_DB_NAME": "${WPDBNameProd}",
          "WP_DB_USER": "${WPDBUserProd}",
          "WP_DB_PASSWORD": "${WPDBPasswordProd}",
          "WP_AUTH_KEY": "${WPAuthKeyProd}",
          "WP_SECURE_AUTH_KEY": "${WPSecureAuthKeyProd}",
          "WP_LOGGED_IN_KEY": "${WPLoggedInKeyProd}",
          "WP_NONCE_KEY": "${WPNonceKeyProd}",
          "WP_AUTH_SALT": "${WPAuthSaltProd}",
          "WP_SECURE_AUTH_SALT": "${WPSecureAuthSaltProd}",
          "WP_LOGGED_IN_SALT": "${WPLoggedInSaltProd}",
          "WP_NONCE_SALT": "${WPNonceSaltProd}"
        }
                
  SecretsManagerSecretStage:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: wordpress/secrets/stage
      Description: Database credentials and salts for wordpress.
      SecretString: !Sub |
        {
          "WP_DB_NAME": "${WPDBNameStage}",
          "WP_DB_USER": "${WPDBUserStage}",
          "WP_DB_PASSWORD": "${WPDBPasswordStage}",
          "WP_AUTH_KEY": "${WPAuthKeyStage}",
          "WP_SECURE_AUTH_KEY": "${WPSecureAuthKeyStage}",
          "WP_LOGGED_IN_KEY": "${WPLoggedInKeyStage}",
          "WP_NONCE_KEY": "${WPNonceKeyStage}",
          "WP_AUTH_SALT": "${WPAuthSaltStage}",
          "WP_SECURE_AUTH_SALT": "${WPSecureAuthSaltStage}",
          "WP_LOGGED_IN_SALT": "${WPLoggedInSaltStage}",
          "WP_NONCE_SALT": "${WPNonceSaltStage}"
        }


Outputs:
  SecretsStage:
    Description: Secrets for stage
    Value: !Ref SecretsManagerSecretStage
    Export:
      Name: !Sub "${AWS::StackName}-SecretsStage"
  SecretsProd:
    Description: Secrets for prod
    Value: !Ref SecretsManagerSecretProd
    Export:
      Name: !Sub "${AWS::StackName}-SecretsProd"