AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets for wordpress docker POC

Parameters:
  WPDBNameStage:
    Type: String
    Description: Database name
  WPDBUserStage:
    Type: String
    Description: Database user
  WPDBPasswordStage:
    Type: String
    Description: Database password
  WPAuthKeyStage:
    Type: String
    Description: Auth key
  WPSecureAuthKeyStage:
    Type: String
    Description: Secure auth Key
  WPLoggedInKeyStage:
    Type: String
    Description: Logged in key
  WPNonceKeyStage:
    Type: String
    Description: Nonce key
  WPAuthSaltStage:
    Type: String
    Description: Auth salt
  WPSecureAuthSaltStage:
    Type: String
    Description: Secure auth salt
  WPLoggedInSaltStage:
    Type: String
    Description: Logged in salt
  WPNonceSaltStage:
    Type: String
    Description: Nonce salt
  WPDBNameProd:
    Type: String
    Description: Database name
  WPDBUserProd:
    Type: String
    Description: Database user
  WPDBPasswordProd:
    Type: String
    Description: Database password
  WPAuthKeyProd:
    Type: String
    Description: Auth key
  WPSecureAuthKeyProd:
    Type: String
    Description: Secure auth Key
  WPLoggedInKeyProd:
    Type: String
    Description: Logged in key
  WPNonceKeyProd:
    Type: String
    Description: Nonce key
  WPAuthSaltProd:
    Type: String
    Description: Auth salt
  WPSecureAuthSaltProd:
    Type: String
    Description: Secure auth salt
  WPLoggedInSaltProd:
    Type: String
    Description: Logged in salt
  WPNonceSaltProd:
    Type: String
    Description: Nonce salt


Resources:
  SSMParameterDBNameProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/dbname
      Description: Database name
      Value: !Ref WPDBNameProd
      Type: String

  SSMParameterDBUserProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/dbuser
      Description: Database user
      Value: !Ref WPDBUserProd
      Type: String
      
  SSMParameterDBPasswordProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/dbpassword
      Description: Database password
      Value: !Ref WPDBPasswordProd
      Type: String

  SSMParameterAuthKeyProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/authkey
      Description: Auth Key
      Value: !Ref WPAuthKeyProd
      Type: String

  SSMParameterSecureAuthKeyProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/secureauthkey
      Description: Secure Auth Key
      Value: !Ref WPSecureAuthKeyProd
      Type: String

  SSMParameterLoggedInKeyProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/loggedinkey
      Description: Logged In Key
      Value: !Ref WPLoggedInKeyProd
      Type: String

  SSMParameterNonceKeyProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/noncekey
      Description: Nonce Key
      Value: !Ref WPNonceKeyProd
      Type: String

  SSMParameterAuthSaltProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/authsalt
      Description: Auth Salt
      Value: !Ref WPAuthSaltProd
      Type: String

  SSMParameterSecureAuthSaltProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/secureauthsalt
      Description: Secure Auth Salt
      Value: !Ref WPSecureAuthSaltProd
      Type: String

  SSMParameterLoggedInSaltProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/loggedinsalt
      Description: Logged In Salt
      Value: !Ref WPLoggedInSaltProd
      Type: String

  SSMParameterNonceSaltProd:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/prod/noncesalt
      Description: Nonce Salt
      Value: !Ref WPNonceSaltProd
      Type: String

  SSMParameterDBNameStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/dbname
      Description: Database name
      Value: !Ref WPDBNameStage
      Type: String

  SSMParameterDBUserStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/dbuser
      Description: Database user
      Value: !Ref WPDBUserStage
      Type: String
      
  SSMParameterDBPasswordStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/dbpassword
      Description: Database password
      Value: !Ref WPDBPasswordStage
      Type: String
      
  SSMParameterAuthKeyStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/authkey
      Description: Auth Key
      Value: !Ref WPAuthKeyStage
      Type: String

  SSMParameterSecureAuthKeyStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/secureauthkey
      Description: Secure Auth Key
      Value: !Ref WPSecureAuthKeyStage
      Type: String

  SSMParameterLoggedInKeyStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/loggedinkey
      Description: Logged In Key
      Value: !Ref WPLoggedInKeyStage
      Type: String

  SSMParameterNonceKeyStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/noncekey
      Description: Nonce Key
      Value: !Ref WPNonceKeyStage
      Type: String

  SSMParameterAuthSaltStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/authsalt
      Description: Auth Salt
      Value: !Ref WPAuthSaltStage
      Type: String

  SSMParameterSecureAuthSaltStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/secureauthsalt
      Description: Secure Auth Salt
      Value: !Ref WPSecureAuthSaltStage
      Type: String

  SSMParameterLoggedInSaltStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/loggedinsalt
      Description: Logged In Salt
      Value: !Ref WPLoggedInSaltStage
      Type: String

  SSMParameterNonceSaltStage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /wordpress/secrets/stage/noncesalt
      Description: Nonce Salt
      Value: !Ref WPNonceSaltStage
      Type: String
