version: "3.7"
services:
  php-fpm:
    build: 
      context: ./php-fpm
      args: 
        NPM_TOKEN: # Your github npm token. TODO can import from local env vars? Some magic?
    volumes:
      - code:/var/www/html
      # - ./php-fpm/app:/var/www/html
    env_file:
      - ./php-fpm/.env
      
  nginx:
    build: 
      context: ./nginx
    links:
      - php-fpm
    volumes:
      - code:/var/www/html
      # - ./php-fpm/app:/var/www/html

  proxy:
    links:
      - nginx
    build: 
      context: ./proxy
    ports:
      - 80:80
      - 443:443
  #mariadb: TODO? 

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      permissions:
        defaultFileMode: 0666
        defaultDirectoryMode: 0777
    wp:
      ignore:
        vcs: true
        paths: # exclude the junk we don't need from being synced
          - "**/node_modules/**"
      alpha: "./php-fpm/app"
      beta: "volume://code"
      mode: "two-way-safe"